# Brews
brew "ansible"
brew "awscli"
brew "cmake"
brew "fish"
brew "gibo"
brew "go"
brew "jq"
brew "mas"
brew "node"
brew "trash"
brew "tree"
brew "wifi-password"
brew "wrk"
brew "yarn"

# Casks
# cask "1password"
cask "appcleaner"
cask "arduino"
cask "docker"
cask "firefox"
cask "font-fira-code"
cask "font-monofur-for-powerline"
cask "gpg-suite"
cask "insomnia"
cask "iterm2"
cask "pock"
cask "protonvpn"
cask "signal"
cask "tableplus"
cask "typora"
cask "visual-studio-code"
cask "vlc"
cask "yed"

# Mac App Store
mas "Keynote", id: 409183694
mas "Microsoft To Do", id: 1274495053
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Xcode", id: 497799835
